Fatal Python error: Segmentation fault

Thread 0x00007fe49a7ffb30 (most recent call first):
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 90 in _worker
  File "/usr/local/lib/python3.13/threading.py", line 992 in run
  File "/usr/local/lib/python3.13/threading.py", line 1041 in _bootstrap_inner
  File "/usr/local/lib/python3.13/threading.py", line 1012 in _bootstrap

Thread 0x00007fe49bcc1b30 (most recent call first):
  <no Python frame>

Thread 0x00007fe49bde0b30 (most recent call first):
  File "/usr/local/lib/python3.13/site-packages/midealocal/device.py", line 262 in authenticate
  File "/usr/local/lib/python3.13/site-packages/midealocal/device.py", line 218 in connect
  File "/usr/local/lib/python3.13/site-packages/midealocal/device.py", line 664 in _connect_loop
  File "/usr/local/lib/python3.13/site-packages/midealocal/device.py", line 707 in run
  File "/usr/local/lib/python3.13/threading.py", line 1041 in _bootstrap_inner
  File "/usr/local/lib/python3.13/threading.py", line 1012 in _bootstrap

Thread 0x00007fe49bfffb30 (most recent call first):
  File "/usr/local/lib/python3.13/site-packages/pycares/__init__.py", line 363 in _run_safe_shutdown_loop
  File "/usr/local/lib/python3.13/threading.py", line 992 in run
  File "/usr/local/lib/python3.13/threading.py", line 1041 in _bootstrap_inner
  File "/usr/local/lib/python3.13/threading.py", line 1012 in _bootstrap

Current thread 0x00007fe49dec0b30 (most recent call first):
  <no Python frame>

Thread 0x00007fe49e0dfb30 (most recent call first):
  File "/usr/local/lib/python3.13/socket.py", line 977 in getaddrinfo
  File "/usr/local/lib/python3.13/socket.py", line 840 in create_connection
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4640 in _create_socket_connection
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 4609 in _create_socket
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1598 in reconnect
  File "/usr/local/lib/python3.13/site-packages/paho/mqtt/client.py", line 1435 in connect
  File "/config/custom_components/xiaomi_home/miot/miot_mips.py", line 757 in __mips_connect
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89 in _run
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2034 in _run_once
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 677 in run_forever
  File "/config/custom_components/xiaomi_home/miot/miot_mips.py", line 634 in __mips_loop_thread
  File "/usr/local/lib/python3.13/threading.py", line 992 in run
  File "/usr/local/lib/python3.13/threading.py", line 1041 in _bootstrap_inner
  File "/usr/local/lib/python3.13/threading.py", line 1012 in _bootstrap

Thread 0x00007fe4b7d7fb38 (most recent call first):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 853 in _run_event_loop
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 812 in _run
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 690 in run
  File "/usr/local/lib/python3.13/threading.py", line 1041 in _bootstrap_inner
  File "/usr/local/lib/python3.13/threading.py", line 1012 in _bootstrap

Thread 0x00007fe4bb3ffb38 (most recent call first):
  File "<frozen importlib._bootstrap_external>", line 166 in _path_stat
  File "<frozen importlib._bootstrap_external>", line 1651 in find_spec
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 2475 in _handle_ns
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 2585 in fixup_namespace_packages
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3143 in activate
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3685 in <genexpr>
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3685 in _initialize_master_working_set
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3644 in _call_aside
  File "/usr/local/lib/python3.13/site-packages/pkg_resources/__init__.py", line 3660 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1026 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/usr/local/lib/python3.13/site-packages/google/__init__.py", line 2 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1026 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1310 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1310 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/usr/local/lib/python3.13/site-packages/pyatv/support/__init__.py", line 11 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1026 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1310 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/usr/local/lib/python3.13/site-packages/pyatv/settings.py", line 7 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1026 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/usr/local/lib/python3.13/site-packages/pyatv/interface.py", line 42 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1026 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1415 in _handle_fromlist
  File "/usr/local/lib/python3.13/site-packages/pyatv/__init__.py", line 14 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1026 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/__init__.py", line 10 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1026 in exec_module
  File "<frozen importlib._bootstrap>", line 935 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1331 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1387 in _gcd_import
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1310 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1360 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1387 in _gcd_import
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88 in import_module
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201 in protected_loop_func
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1282 in _import_platform
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1250 in _load_platform
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1076 in _load_platforms
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59 in run
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 93 in _worker
  File "/usr/local/lib/python3.13/threading.py", line 992 in run
  File "/usr/local/lib/python3.13/threading.py", line 1041 in _bootstrap_inner
  File "/usr/local/lib/python3.13/threading.py", line 1012 in _bootstrap

Thread 0x00007fe4bbdffb38 (most recent call first):
  File "<frozen importlib._bootstrap_external>", line 1632 in find_spec
  File "<frozen importlib._bootstrap_external>", line 1533 in _get_spec
  File "<frozen importlib._bootstrap_external>", line 197 in find_spec
  File "<frozen importlib._bootstrap>", line 1282 in _find_spec
  File 